spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
#          uri: file:///D:\Suresh\Java-Training-Workspace\SpringBoot-Microservices-Training\25-Jan-2021\config-repo
            uri: https://github.com/sureshstalin/configs.git
            default-label: master
            username: sureshstalin
            password: kesavan123$$
server:
  port: 8888
#eureka:
#  instance:
#    hostname: 65.1.222.21
#  client:
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
eureka:
  instance:
    hostname: 65.1.222.21
  client:
    serviceUrl:
      defaultZone: http://65.1.222.21:8761/eureka/
#spring.cloud.config.server.git.uri=https://github.com/sureshstalin/config-files.git
#spring.cloud.config.server.git.username=suresh_stalin
#spring.cloud.config.server.git.password=kesavan123$$
#spring.cloud.config.server.git.uri=file:///C:/Users/ssure/test-files

#spring.cloud.config.server.git.username=ssuresh.saikishore@gmail.com
#spring.cloud.config.server.git.password=kesavan123$$
#spring.cloud.config.server.bootstrap=true
